plugins {
    id 'de.featjar.java-library'
}

dependencies {
    api 'de.featjar:formula'
    api 'de.featjar:feature-model'
    // implementation 'io.github.universal-variability-language:fm-metamodel:1.1'
    implementation files('lib/fm-metamodel-1.1-jar-with-dependencies.jar')
    testImplementation 'de.featjar:formula-analysis-sat4j'
    testImplementation 'de.featjar:formula-analysis-javasmt'
    testImplementation testFixtures('de.featjar:formula')
}

license {
    ext {
        licence_url = 'https://github.com/FeatureIDE/FeatJAR-uvl'
    }
}
