FROM maven:3.8.6-openjdk-11
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    libgmp-dev
WORKDIR /home
RUN git clone https://github.com/FeatJAR/FeatJAR.git \
  && git -C FeatJAR checkout {COMMIT}
WORKDIR /home/FeatJAR
{MODULES}
RUN make
COPY docker ./{MODULE}
RUN make install:{MODULE}
