#!/bin/zsh
COLOR='\033[0;32m'
NOCOLOR='\033[0m'

ROOT_DIR="${PWD}"

find . -name ".git" -type d -print0 | sort -z | while read -d $'\0' GIT_DIR
do
    CUR_DIR="$(dirname "${GIT_DIR}")"
    CUR_DIR=$(realpath --relative-to="${ROOT_DIR}" "${CUR_DIR}")
    printf "%-40s" `echo -e "${COLOR}${CUR_DIR}${NOCOLOR}"`
    cd "${CUR_DIR}"
    git status -s -uno -b --ahead-behind
    cd "${ROOT_DIR}"
done
