#!/bin/zsh
COLOR='\033[0;32m'
NOCOLOR='\033[0m'

ROOT_DIR="${PWD}"

if [ -z "$LOCAL_SSHKEY_SAVED" ]; then eval $(ssh-agent) && ssh-add && LOCAL_SSHKEY_SAVED=1 && export LOCAL_SSHKEY_SAVED; fi

find . -name ".git" -type d -print0 | while read -d $'\0' GIT_DIR
do
    CUR_DIR="$(dirname "${GIT_DIR}")"
    CUR_DIR=$(realpath --relative-to="${ROOT_DIR}" "${CUR_DIR}")
    echo -e "${COLOR}${CUR_DIR}${NOCOLOR}"
    cd "${CUR_DIR}"
    git pull -4
    cd "${ROOT_DIR}"
done

